version: '3'

services:
  chat-app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - ~/.aws:/root/.aws:ro  # Mount AWS credentials
    env_file:
      - .env
    environment:
      - AWS_REGION=${AWS_REGION:-us-west-2}
    restart: unless-stopped
